bm = [ \
       'BBBBBYYYYYYYYBBB' \
       'BBBYYYBBBBBBYYBB' \
       'BBBYBBBBBBBBBYYB' \
       'BBYYBBBBBBBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBLBBLBBBBYB' \
       'BBYBBBLBBLBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBRBRBRBRBBYB' \
       'BBYBBBRBRBRBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBYYBYBYBYYYYB' \
       'BBYYBBYBYYYBYBYB' \
       'BBBBBBBBBBBBBBBB'
      ,
       'BBBBBYYYYYYYYBBB' \
       'BBBYYYBBBBBBYYBB' \
       'BBBYBBBBBBBBBYYB' \
       'BBYYBBBBBBBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBBLBBLBBBYB' \
       'BBYBBBBLBBLBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBRBRBRBBBYB' \
       'BBYBBRBRBRBRBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYBBBBBBBBBBBYB' \
       'BBYYBBYBYYYBYBYB' \
       'BBYBYYBYBYBYYYYB' \
       'BBBBBBBBBBBBBBBB'
     ]
